version: 2

jobs:
  build:
    working_directory: ~/island-troll-tribes

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - run:
          name: Install Wurst
          command: |
            mkdir $HOME/.wurst/
            wget https://grill.wurstlang.org/hudson/job/WurstSetup/lastSuccessfulBuild/artifact/downloads/WurstSetup.jar -O $HOME/.wurst/WurstSetup.jar
            java -jar $HOME/.wurst/WurstSetup.jar install wurstscript

      - run:
          name: Update Dependencies
          command: |
            rm $HOME/.gitconfig
            java -jar $HOME/.wurst/WurstSetup.jar update

      - run:
          name: Test
          command: |
            java -jar $HOME/.wurst/wurstscript.jar $HOME/.wurst/common.j $HOME/.wurst/blizzard.j ./ -runcompiletimefunctions -runtests
